"""Models: Entrance, Spot, & Distance.

Revision ID: 12e3930ec23e
Revises: 3ca8eb27e66a
Create Date: 2022-02-06 18:26:06.771044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e3930ec23e'
down_revision = '3ca8eb27e66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot',
    sa.Column('id', sa.String(length=256), autoincrement=False, nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('updated_by', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('distance',
    sa.Column('id', sa.String(length=256), autoincrement=False, nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('entrance', sa.String(length=256), nullable=False),
    sa.Column('spot', sa.String(length=256), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('updated_by', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entrance'], ['entrance.id'], ),
    sa.ForeignKeyConstraint(['spot'], ['spot.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'entrance', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'entrance', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entrance', type_='foreignkey')
    op.drop_constraint(None, 'entrance', type_='foreignkey')
    op.drop_table('distance')
    op.drop_table('spot')
    # ### end Alembic commands ###
