"""Removed salt from User.

Revision ID: 3533198bd470
Revises: 7161f6f1ffa8
Create Date: 2022-02-06 10:19:32.011602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3533198bd470'
down_revision = '7161f6f1ffa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'entrance', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'entrance', 'user', ['updated_by'], ['id'])
    op.drop_index('salt', table_name='user')
    op.drop_column('user', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', mysql.VARCHAR(length=256), nullable=True))
    op.create_index('salt', 'user', ['salt'], unique=False)
    op.drop_constraint(None, 'entrance', type_='foreignkey')
    op.drop_constraint(None, 'entrance', type_='foreignkey')
    # ### end Alembic commands ###
