"""Added model Parking.

Revision ID: 609163271cf0
Revises: 3028d5b6028e
Create Date: 2022-02-07 03:50:16.483958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609163271cf0'
down_revision = '3028d5b6028e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking',
    sa.Column('id', sa.String(length=256), autoincrement=False, nullable=False),
    sa.Column('vehicle_plateno', sa.String(length=20), nullable=False),
    sa.Column('vehicle_size', sa.Integer(), nullable=False),
    sa.Column('entrance_id', sa.String(length=256), nullable=False),
    sa.Column('spot_id', sa.String(length=256), nullable=False),
    sa.Column('spot_size', sa.String(length=256), nullable=False),
    sa.Column('parked_on', sa.DateTime(), nullable=True),
    sa.Column('parked_off', sa.DateTime(), nullable=True),
    sa.Column('total_fee', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('updated_by', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entrance_id'], ['entrance.id'], ),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], ),
    sa.ForeignKeyConstraint(['spot_size'], ['spot.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_plateno')
    )
    op.create_foreign_key(None, 'distance', 'entrance', ['entrance'], ['id'])
    op.create_foreign_key(None, 'distance', 'spot', ['spot'], ['id'])
    op.create_foreign_key(None, 'distance', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'distance', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'entrance', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'entrance', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'spot', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'spot', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spot', type_='foreignkey')
    op.drop_constraint(None, 'spot', type_='foreignkey')
    op.drop_constraint(None, 'entrance', type_='foreignkey')
    op.drop_constraint(None, 'entrance', type_='foreignkey')
    op.drop_constraint(None, 'distance', type_='foreignkey')
    op.drop_constraint(None, 'distance', type_='foreignkey')
    op.drop_constraint(None, 'distance', type_='foreignkey')
    op.drop_constraint(None, 'distance', type_='foreignkey')
    op.drop_table('parking')
    # ### end Alembic commands ###
