"""Readjusted user fullname.

Revision ID: 7161f6f1ffa8
Revises: 761e61f219ba
Create Date: 2022-02-04 19:03:08.673000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7161f6f1ffa8'
down_revision = '761e61f219ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'entrance', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'entrance', 'user', ['created_by'], ['id'])
    op.alter_column('user', 'fullname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'fullname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'entrance', type_='foreignkey')
    op.drop_constraint(None, 'entrance', type_='foreignkey')
    # ### end Alembic commands ###
