"""Added user fullname.

Revision ID: 761e61f219ba
Revises: 176855d55720
Create Date: 2022-02-04 19:00:50.722747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761e61f219ba'
down_revision = '176855d55720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'entrance', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'entrance', 'user', ['created_by'], ['id'])
    op.add_column('user', sa.Column('fullname', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'user', ['fullname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'fullname')
    op.drop_constraint(None, 'entrance', type_='foreignkey')
    op.drop_constraint(None, 'entrance', type_='foreignkey')
    # ### end Alembic commands ###
