"""Testing relationship.

Revision ID: 8a85bb640997
Revises: f00d1256782e
Create Date: 2022-02-09 20:52:10.958821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a85bb640997'
down_revision = 'f00d1256782e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('entrance_ibfk_1', 'entrance', type_='foreignkey')
    op.drop_column('entrance', 'updated_by')
    op.create_foreign_key(None, 'parking', 'spot', ['spot_size'], ['id'])
    op.create_foreign_key(None, 'parking', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'parking', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'parking', 'entrance', ['entrance_id'], ['id'])
    op.create_foreign_key(None, 'parking', 'spot', ['spot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.add_column('entrance', sa.Column('updated_by', mysql.VARCHAR(length=256), nullable=False))
    op.create_foreign_key('entrance_ibfk_1', 'entrance', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###
