"""Set table to dynamic.

Revision ID: f00d1256782e
Revises: 63fea768a088
Create Date: 2022-02-09 20:22:05.890066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00d1256782e'
down_revision = '63fea768a088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'parking', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'parking', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'parking', 'spot', ['spot_id'], ['id'])
    op.create_foreign_key(None, 'parking', 'entrance', ['entrance_id'], ['id'])
    op.create_foreign_key(None, 'parking', 'spot', ['spot_size'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    # ### end Alembic commands ###
