"""Remove updated_by column.

Revision ID: f8c42624ee1d
Revises: 8a85bb640997
Create Date: 2022-02-10 03:05:00.915186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8c42624ee1d'
down_revision = '8a85bb640997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('distance_ibfk_2', 'distance', type_='foreignkey')
    op.drop_column('distance', 'updated_by')
    op.create_foreign_key(None, 'parking', 'entrance', ['entrance_id'], ['id'])
    op.create_foreign_key(None, 'parking', 'spot', ['spot_id'], ['id'])
    op.create_foreign_key(None, 'parking', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'parking', 'spot', ['spot_size'], ['id'])
    op.create_foreign_key(None, 'parking', 'user', ['updated_by'], ['id'])
    op.drop_constraint('spot_ibfk_2', 'spot', type_='foreignkey')
    op.drop_column('spot', 'updated_by')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'updated_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_by', mysql.VARCHAR(length=256), nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'user', ['updated_by'], ['id'])
    op.add_column('spot', sa.Column('updated_by', mysql.VARCHAR(length=256), nullable=False))
    op.create_foreign_key('spot_ibfk_2', 'spot', 'user', ['updated_by'], ['id'])
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.add_column('distance', sa.Column('updated_by', mysql.VARCHAR(length=256), nullable=False))
    op.create_foreign_key('distance_ibfk_2', 'distance', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###
